version: '3.8'
services:
  db:
    image: postgres:15
    container_name: logistic_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=logistic_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

volumes:
  postgres_data_new: